M48
; DRILL file {KiCad 9.0.7} date 2026-01-19T10:27:03-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-19T10:27:03-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X168.82Y-88.11
X168.82Y-93.89
T2
X122.75Y-96.25
X172.0Y-81.25
X172.25Y-124.75
M30
