M48
; DRILL file {KiCad 9.0.2} date 2025-06-22T20:13:19-0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-22T20:13:19-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X168.82Y-88.11
X168.82Y-93.89
T2
X122.75Y-96.25
X172.0Y-81.25
X172.25Y-124.75
M30
